name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Repo
      uses: actions/checkout@v1
    - name: Set Up Node
      uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm run install-dependencies
    - name: React Build
      run: npm run build
