name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
    - name: install
      run: npm run install-dependencies
    - name: build
      run: npm run build
