name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: actions/checkout@v1
      - name: Set Up Node
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm i && npx lerna exec -- npm i
      - name: Build
        run: npm run build
      - name: Install Production Dependencies
        run: npm run clean && npm i && npx lerna exec -- npm i --production
      - name: Deploy
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: sh ./deploy.sh
