name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://node:lts-alpine
    - name: install
      run: npm run install-dependencies
    - name: build
      run: npm run build
